export default {
    accepted: "الحقل :attribute يجب أن تكون مقبولة",
    after: "الحقل :attribute يجب أن تكون بعد الحقل :after.",
    after_or_equal: "الحقل :attribute يجب أن تكون مساوية أو بعد الحقل :after_or_equal.",
    alpha: "الحقل  :attribute يجب أن تحتوي على أحرف فقط",
    alpha_dash: "الحقل :attribute مسموح بأن يحتوي على حروف و أرقام و شرطة و شرطة منخفضة",
    alpha_num: "الحقل :attribute يجب أن يحتوي على أحرف و أرقام",
    before: "الحقل :attribute يجب أن تكون قبل :before.",
    before_or_equal: "الحقل :attribute يجب أن تكون مساوية أو قبل الحقل :before_or_equal.",
    between: "الحقل :attribute يجب أن يكون بين :min و :max.",
    confirmed: "تأكيد الحقل :attribute غير متطابق.",
    email: "الحقل :attribute صيغتها غير صحيحة",
    date: "الحقل :attribute صيغتها ليست تاريخ صحيح",
    def: "الحقل :attribute تحتوي على أخطاء",
    digits: "الحقل :attribute يجب أن تكون :digits أرقام.",
    digits_between: "يجب أن يحتوي :attribute بين :min و :max رقمًا/أرقام .",
    different: "الحقل :attribute و الحقل :different يجب أن تكونا مختلفتين",
    in: "الحقل :attribute المختارة، غير صحيحة.",
    integer: "الحقل :attribute يجب أن تكون عدد صحيح",
    hex: "الحقل :attribute يجب أن يحتوي على صيغة هكسيديسمل",
    min: {
        numeric: "الحقل :attribute يجب أن تكون :min على الأقل",
        string: "الحقل :attribute يجب أن تكون :min حرف على الأقل."
    },
    max: {
        numeric: "الحقل :attribute لا يمكن أن تكون أكبر من  :max.",
        string: "الحقل :attribute يجب أن لا تكون أكثر من :max حرف."
    },
    not_in: "الحقل :attribute المختارة غير صحيحة.",
    numeric: "الحقل :attribute يجب أن تكون رقما.",
    present: "الحقل :attribute يجب أن يكون معرفا ، يمكن أن يكون فارغا.",
    required: "الحقل :attribute مطلوب.",
    required_if: "الحقل :attribute مطلوب حين تكون قيمة الحقل :other تساوي :value.",
    required_unless: "الحقل :attribute مطلوب حين تكون قيم الحقل :other لا تساوي :value.",
    required_with: "الحقل :attribute مطلوب حين يكون الحقا :field غير فارغ.",
    required_with_all: "الحقل :attribute مطلوب حين تكون الحقول :fields غير فارغة.",
    required_without: "الحقل :attribute مطلوب حين يكون الحقل :field فارغا.",
    required_without_all: "الحقل :attribute مطلوب حين تكون الحقول :fields فارغة.",
    same: "الحقل :attribute و الحقل :same يجب أن يتطابقا.",
    size: {
        numeric: "الحقل :attribute يجب أن تكون :size.",
        string: "الحقل :attribute يجب أن تكون :size حرفا."
    },
    string: "الحقل :attribute يجب أن تكون نص.",
    url: "الحقل :attribute صياغتها غير صحيحة.",
    regex: "الحقل :attribute صياغتها غير صحيحة.",
    attributes: {
        username: "اسم المستخدم",
        password: "كلمة المرور",
        email: "البريد الالكتروني",
        website: "الموقع الالكتروني",
        firstname: "الاسم الاول",
        lastname: "الاسم الاخير",
        subject: "الموضوع",
        city: "المدينة",
        region: "المنطقة",
        country: "الدولة",
        street: "الشارع",
        zipcode: "الرمز البريدي",
        phone: "رقم الهاتف",
        mobile: "رقم الجوال"
    }
};
